version: '3'
services:
  mongo:
    image: 'mongo:latest'
    restart: always
    ports:
      - 27017:27017 # exposed just on DEV env
    environment:
      MONGO_INITDB_ROOT_USERNAME: buyFood
      MONGO_INITDB_ROOT_PASSWORD: buyFood
  nginx:
    depends_on:
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    # ports:
    #   - '3333:3333' # exposed just on DEV env
    environment:
      - MONGO_USER=buyFood
      - MONGO_PASSWORD=buyFood
  client:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
